credentials:
  usernames:
    user1:
      name: "cemcvs"
      password: "cemcvs1234"
    user2:
      name: "alifurkan"
      password: "alifurkan1234"
cookie:
  expiry_days: 30
  key: "123456"
